apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: final
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    name: newapp
  type: NodePort
